# Generated by Django 3.0.7 on 2022-02-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudapp',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cloudapp',
            name='thumbnail',
            field=models.ImageField(upload_to='images/upload/%Y/%m/%d/'),
        ),
    ]
